# Generated by Django 3.2.8 on 2021-11-07 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_contactus'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactUs',
            new_name='ContactList',
        ),
    ]
